name: Bad Sector Security
favicon: null
layout_spectrum: 0.14948
typography_spectrum: 0
title: I Talk to Machines
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#767b7f'
    - '#0291b4'
    - '#eef2f3'
    - '#9ec6da'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.7340036635287106
purpose: []
