name: Bad Sector Security
favicon: null
layout_spectrum: 0.9674445583950728
typography_spectrum: 0.017405277583748102
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#3c2f1c'
    - '#d8cba5'
    - '#687d86'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.7340036635287106
purpose: []
