name: Bad Sector Security
favicon: null
layout_spectrum: 0.9674445583950728
typography_spectrum: 0.017405277583748102
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8983683080878109
  lightness: 0.4573240326717496
  saturation: 0.7477910171728581
  rhythmicContrast: 0.7340036635287106
purpose: []
